# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekof', models.DateField()),
                ('favorite', models.CharField(max_length=30)),
                ('dog', models.CharField(max_length=30)),
                ('line', models.IntegerField(default=0)),
                ('ou', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekof', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('correct', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekof', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laxbets_app.Game')),
            ],
        ),
    ]
