# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxbets_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='weekof',
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='submission',
            name='pick',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='week',
            name='games',
            field=models.ManyToManyField(to='laxbets_app.Game'),
        ),
    ]
