# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxbets_app', '0002_auto_20180305_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='line',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='ou',
            field=models.FloatField(default=0),
        ),
    ]
