# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laxbets_app', '0005_auto_20180305_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laxbets_app.Game')),
                ('pick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laxbets_app.Team')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyPicks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('picks', models.ManyToManyField(to='laxbets_app.Pick')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laxbets_app.Week')),
            ],
        ),
        migrations.RemoveField(
            model_name='playerweek',
            name='picks',
        ),
        migrations.RemoveField(
            model_name='playerweek',
            name='week',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='game',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='pick',
        ),
        migrations.DeleteModel(
            name='PlayerWeek',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
