# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-30 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxbets_app', '0008_week_cutofftime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='cutoffTime',
            field=models.DateTimeField(),
        ),
    ]
