# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxbets_app', '0009_auto_20180330_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersubmission',
            name='winners',
            field=models.IntegerField(default=0),
        ),
    ]
