# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laxbets_app', '0012_auto_20180331_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='laxbets_app.Team'),
        ),
    ]
