# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxbets_app', '0013_auto_20180331_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='correct',
            field=models.IntegerField(default=0),
        ),
    ]
