# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laxbets_app', '0014_pick_correct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pick',
            old_name='pick',
            new_name='selection',
        ),
    ]
